GET http://localhost:8080/api/v1/clientes
### Enviar novo cliente
POST http://localhost:8080/api/v1/clientes
Content-Type: application/json

{
    "CPF": "124.354.768-01",
    "nome": "Juquinha",
    "dataCadastro": "2022-10-02"
}

### Alterar um cliente
PUT http://localhost:8080/api/v1/clientes/1
Content-Type: application/json

{
    "CPF": "124.354.768-01",
    "nome": "Juca Da Silveira",
    "dataCadastro": "2022-09-12",
}

### Remover Cliente
DELETE http://localhost:8080/api/v1/clientes/1
